### ISSUE TITLE
How to simulate the permeability of digital cores one by one?

### ISSUE THREAD

**Issue by eromanga233** [yjhp1016/taichi_LBM3D#32]
老师您好~
我在使用LBM进行批量模拟数字岩心的绝对渗透率时，经常会遇到一个报错
`Traceback (most recent call last):
  File "/lustre/home/2001110637/LBM/LBM.py", line 1067, in <module>
    init()
  File "/lustre/home/2001110637/.conda/envs/test/lib/python3.11/site-packages/taichi/lang/kernel_impl.py", line 1113, in wrapped
    return primal(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/home/2001110637/.conda/envs/test/lib/python3.11/site-packages/taichi/lang/kernel_impl.py", line 1045, in __call__
    return self.launch_kernel(kernel_cpp, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/home/2001110637/.conda/envs/test/lib/python3.11/site-packages/taichi/lang/kernel_impl.py", line 976, in launch_kernel
    raise e from None
  File "/lustre/home/2001110637/.conda/envs/test/lib/python3.11/site-packages/taichi/lang/kernel_impl.py", line 971, in launch_kernel
    prog.launch_kernel(compiled_kernel_data, launch_ctx)
RuntimeError: [cuda_driver.h:operator()@92] CUDA Error CUDA_ERROR_ASSERT: device-side assert triggered while calling stream_synchronize (cuStreamSynchronize)
[E 09/15/24 15:35:51.915 1670557] [cuda_driver.h:operator()@92] CUDA Error CUDA_ERROR_ASSERT: device-side assert triggered while calling stream_synchronize (cuStreamSynchronize)

[E 09/15/24 15:35:51.981 1670557] [cuda_driver.h:operator()@92] CUDA Error CUDA_ERROR_ASSERT: device-side assert triggered while calling mem_free (cuMemFree_v2)
terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
/var/spool/slurmd/job3810620/slurm_script: line 10: 1670557 Aborted                 (core dumped) python LBM.py`

我不清楚这个问题的根源是什么，希望您能解疑答惑

**Comment by yjhp1016** [comment]
根据报错和CUDA有关，我也不是太清楚，我感觉是不是和显存有关，你的模型多大？可能超显存了我感觉。。。

eromanga233 ***@***.***> 于 2024年9月15日周日 上午8:48写道：
